set timeout 2

send_user "=== Test xover command ===\n"

spawn telnet $env(nntp_address) 119

send_user "== Check response of xover command without group ==\n"
send "xover\n"
expect {
  timeout { send_user "Error: xover command did not respond correctly\n"; exit 1 }
  -re "412 no news group current selected"
}

send_user "== Check response of xover command with group without article ==\n"
send "group alt.wendzelnntpd.test.empty\n"
send "xover\n"
expect {
  timeout { send_user "Error: xover command did not respond correctly\n"; exit 1 }
  -re "420 no \\(current\\) article selected"
}

send_user "== Check response of xover command with group with article ==\n"
send "group alt.wendzelnntpd.test\n"
send "xover\n"
expect {
  timeout { send_user "Error: xover command did not respond correctly\n"; exit 1 }
  -re "224 overview information follows\\r\\n1\[\\t\]Test\[\\t\]Testuser <test@example.com>\[\\t\]"
}

send_user "== Check response of xover command with group with article2 ==\n"
send "xover\n"
expect {
  timeout { send_user "Error: xover command did not respond correctly\n"; exit 1 }
  -re "224 overview information follows\\r\\n1\[\\t\]Test\[\\t\]Testuser <test@example.com>\[\\t\]Sat, 28 Jun 2025"
}

send_user "== Check response of xover command with group with article3 ==\n"
send "xover\n"
expect {
  timeout { send_user "Error: xover command did not respond correctly\n"; exit 1 }
  -re "224 overview information follows\\r\\n1\[\\t\]Test\[\\t\]Testuser <test@example.com>\[\\t\]Sat, 28 Jun 2025 12:30:00"
}

send_user "== Check response of xover command with group with article4 ==\n"
send "xover\n"
expect {
  timeout { send_user "Error: xover command did not respond correctly\n"; exit 1 }
  -re "224 overview information follows\\r\\n1\[\\t\]Test\[\\t\]Testuser <test@example.com>\[\\t\]Sat, 28 Jun 2025 12:30:00 \\+0200"
}

send_user "== Check response of xover command with group with article5 ==\n"
send "xover\n"
expect {
  timeout { send_user "Error: xover command did not respond correctly\n"; exit 1 }
  -re "224 overview information follows\\r\\n1\[\\t\]Test\[\\t\]Testuser <test@example.com>\[\\t\]Sat, 28 Jun 2025 12:30:00 \\+0200\\s<cdp1@localhost>"
}
